name = "FinEtoolsHeatDiff"
uuid = "972d1c22-8bdd-11e9-11cf-cdcb7577b041"
authors = ["Petr Krysl <pkrysl@ucsd.edu>"]
version = "0.3.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FinEtools = "91bb5406-6c9a-523d-811d-0644c4229550"
Gnuplot = "dc211083-a33a-5b79-959f-2ff34033469d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Arpack = "^0.4"
FinEtools = "^4.7"
julia = "^1.5"
